version: 0.2  # Recommended to use 0.2 instead of 0.1

env:
  secrets-manager:
    TOKEN: Sonartoken:Sonartoken


phases:
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=javaprojectaws-x_devsecopsaws -Dsonar.organization=javaprojectaws-x -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$TOKEN
